spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hanbui
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000s

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: http://localhost:8080

sendgrid:
  api-key: ${SENDGRID_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}