spring:
  application:
    name: backend-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hanbui
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
jwt:
  secret-key: ${JWT_SECRET_KEY}